spectaql:
  logoFile: ./test/fixtures/logo.png
  faviconFile: ./test/fixtures/favicon.png
  displayAllServers: true

introspection:
  removeTrailingPeriodFromDescriptions: false
  schemaFile: ./src/typedefs/schema.gql
  metadataFile: ./util/userdatabase.json
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2

  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: WonderPet GraphQL API Reference
  description: Takeaway Homework creating a server via Node.js + Typescript + apollo-server
  contact:
    name: Jimmy
    url: https://github.com/JIMMYOOOPS/wonderpets
    email: jimmy85030@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:3000/graphql
    description: Production
    production: true
